FROM confluentinc/cp-kafka-connect-base:latest

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components,/data/connect-jars"

RUN confluent-hub install --no-prompt datastax/kafka-connect-cassandra-sink:1.4.0
